name: example
description: Example app.
version: 1.0.0
publish_to: "none"

environment:
    sdk: ">=3.1.2 <4.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    lordicon:
        path: ../

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    
dependency_overrides:
  archive: ^3.6.1

flutter:
    uses-material-design: true

    assets:
        - assets/camera.json
        - assets/trash.json
        - assets/lock.json
        - assets/lock-alt.json
