name: lordicon
description: This library allows you to easily integrate the playback of Lordicon icons into a Flutter application.
version: 1.0.3
homepage: https://lordicon.com/
repository: https://github.com/lordicondev/lordicon-flutter
issue_tracker: https://github.com/lordicondev/lordicon-flutter/issues

environment:
    sdk: "^3.0.0"

dependencies:
    flutter:
        sdk: flutter
    path: ^1.8.0
    lottie: ^3.1.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

dependency_overrides:
  archive: ^3.6.1

topics:
    - lordicon
    - lottie
    - icon
    - animation
